name: csharp-extensions-configuration-infisical

on:
  push:
    paths:
    - 'CSharp/SandwhichStack.Extensions.Configuration.Infisical/**'
    - 'CSharp/build/**'
    - '.github/workflows/csharp-extensions-configuration-infisical.yml'
    - 'GitVersion.yml'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  GIT_DEPTH: "0" # Needed for GitVersion

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build
        run: |
          ./build.sh --target PackExtensionsConfigurationInfisical NugetPush
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
