name: docker-dotnet-sdk-kaniko

on:
  push:
    paths:
    - 'Docker/dotnet-sdk-kaniko/**'
    - 'CSharp/build/**'
    - '.github/workflows/docker-dotnet-sdk-kaniko.yml'
    - 'GitVersion.yml'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  GIT_DEPTH: "0" # Needed for GitVersion

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build
        run: ./build.sh --target BuildDockerDotnetSdkKaniko PushDockerDotnetSdkKaniko
