name: docker-dotnet-sdk-playwright

on:
  push:
    paths:
    - 'Docker/dotnet/sdk-playwright/**'
    - 'CSharp/build/**'
    - '.github/workflows/docker-dotnet-sdk-playwright.yml'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  GIT_DEPTH: "0" # Needed for GitVersion

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build
        run: ./build.sh --target BuildDockerDotnetSdkPlaywright

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: PushDockerDotnetSdkPlaywright
        run: ./build.sh --target PushDockerDotnetSdkPlaywright
