name: docker-dotnet-sdk-playwright

on:
  push:
    paths:
    - 'Docker/docker/bash/**'
    - 'CSharp/build/**'
    - '.github/workflows/docker-docker-bash.yml'
    - 'GitVersion.yml'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  GIT_DEPTH: "0" # Needed for GitVersion

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build
        run: ./build.sh --target BuildDockerDockerBash PushDockerDockerBash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
