name: main

on: [push, pull_request]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  GIT_DEPTH: "0" # Needed for GitVersion

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build
        run: ./build.sh --target Version Compile

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Test
        run: |
          ./build.sh --target InstallPlaywright Compile Test Coverage
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./artifacts/test-results/
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./artifacts/coverage-report/Cobertura.xml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack
        run: ./build.sh --target Pack Push
